#!/usr/bin/env python3
"""Turns texedit/quest-icons/*.png (NNN.png: sprites cut out of the base game's and Lost in Astral's quest map textures by
_cpr/claude-re/questmap/harvest4.py, pixel for pixel, numbered by first map and position; roll-*.png: the scroll ends) into
texedit/quest_icons_generated.hpp, which the Texture Editor compiles in. Run from tools/um-multitool:
    python3 texedit/gen_quest_icons.py
To add a sprite: cut it out in the Texture Editor (Stamp from the selection), put the PNG in quest-icons/, run this."""
import glob, os
from PIL import Image
out = ['// Generated by gen_quest_icons.py from quest-icons/*.png: do not edit.', '#pragma once', '#include <cstdint>', 'namespace questmap {',
       'struct IconData { const char* name; int w, h; const uint8_t* rgba; };']
items = []
for f in sorted(glob.glob(os.path.join(os.path.dirname(__file__), 'quest-icons', '*.png'))):
    name = os.path.splitext(os.path.basename(f))[0]
    im = Image.open(f).convert('RGBA')
    ident = 'k' + ''.join(c if c.isalnum() else '_' for c in name)
    data = ','.join(str(b) for b in im.tobytes())
    out.append(f'static const uint8_t {ident}[] = {{{data}}};')
    items.append(f'{{"{name}", {im.width}, {im.height}, {ident}}}')
out.append('static const IconData kIcons[] = {' + ','.join(items) + '};')
out.append('} // namespace questmap')
open(os.path.join(os.path.dirname(__file__), 'quest_icons_generated.hpp'), 'w').write('\n'.join(out) + '\n')
print(len(items), 'icons')
