// Auto-generated from tools/ei-um-autopacker/bin/eidbeditor-144/dbtypes.txt and dbblocks.txt
// Do not hand-edit; see docs/file-formats/database-format.md for the source schema tables.
static const std::map<std::string, std::map<int, std::vector<FieldDef>>> DBTYPES = {
    {"Items", {
        {1, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::String, 0}, {3, FieldType::SignedLong, 0}, {4, FieldType::Float, 0}, {5, FieldType::Float, 0}, {6, FieldType::Float, 0}, {7, FieldType::SignedLong, 0}, {8, FieldType::Float, 0}, {9, FieldType::SignedLong, 0}, {10, FieldType::Float, 0}, {11, FieldType::FloatList, 0}, {12, FieldType::SignedLong, 0}, {13, FieldType::BitList, 5} }},
        {2, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::SignedLong, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::Float, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::BitList, 5}, {15, FieldType::Byte, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::FloatList, 0}, {23, FieldType::Float, 0}, {24, FieldType::Float, 0}, {25, FieldType::Float, 0}, {26, FieldType::FloatList, 0}, {27, FieldType::Hex, 0}, {28, FieldType::Hex, 0}, {29, FieldType::Float, 0}, {30, FieldType::Float, 0} }},
        {3, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::SignedLong, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::Float, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::BitList, 5}, {15, FieldType::Byte, 0}, {21, FieldType::FloatList, 0}, {22, FieldType::FloatList, 0}, {23, FieldType::Byte, 0}, {24, FieldType::SignedLong, 0}, {25, FieldType::Hex, 0}, {26, FieldType::Hex, 0} }},
        {4, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::SignedLong, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::Float, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::BitList, 5}, {15, FieldType::Byte, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::SignedLong, 0}, {23, FieldType::Float, 0}, {24, FieldType::Float, 0}, {25, FieldType::String, 0}, {26, FieldType::ByteList, 0}, {27, FieldType::Hex, 0} }},
        {5, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::SignedLong, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::Float, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::BitList, 5}, {15, FieldType::Byte, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::StringList, 0} }},
        {6, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::SignedLong, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::Float, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::BitList, 5}, {15, FieldType::Byte, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::Hex, 0}, {23, FieldType::SignedLong, 0} }},
    }},
    {"Levers", {
        {1, { {0, FieldType::String, 0}, {1, FieldType::FloatList, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::Float, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::String, 0}, {6, FieldType::String, 0}, {7, FieldType::String, 0} }},
    }},
    {"Perks", {
        {1, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {10, FieldType::StringList, 0} }},
        {2, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {10, FieldType::String, 0}, {11, FieldType::String, 0}, {12, FieldType::SignedLong, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::SignedLong, 0}, {15, FieldType::Float, 0}, {16, FieldType::Float, 0}, {17, FieldType::Float, 0}, {18, FieldType::SignedLong, 0}, {19, FieldType::SignedLong, 0}, {20, FieldType::SignedLong, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::Byte, 0}, {23, FieldType::SignedLong, 0} }},
    }},
    {"Prints", {
        {1, { {1, FieldType::String, 0}, {2, FieldType::TypeList, 20}, {3, FieldType::TypeList, 20} }},
        {2, { {1, FieldType::String, 0}, {2, FieldType::TypeList, 20}, {3, FieldType::TypeList, 20}, {10, FieldType::TypeList, 20} }},
        {3, { {1, FieldType::String, 0}, {2, FieldType::TypeList, 20}, {3, FieldType::TypeList, 20} }},
        {20, { {1, FieldType::Float, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::SignedLong, 0} }},
    }},
    {"Spells", {
        {1, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::String, 0}, {3, FieldType::Float, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::Float, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::Float, 0}, {8, FieldType::Float, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::SignedLong, 0}, {12, FieldType::SignedLong, 0}, {13, FieldType::SignedLong, 0}, {14, FieldType::SignedLong, 0}, {15, FieldType::UnsignedLong, 0}, {16, FieldType::MinfixedStringList, 4}, {17, FieldType::MinfixedStringList, 4}, {18, FieldType::SignedLong, 0}, {19, FieldType::SignedLong, 0}, {20, FieldType::ByteList, 0}, {21, FieldType::SignedLong, 0}, {22, FieldType::BitList, 5}, {23, FieldType::Float, 0}, {24, FieldType::Float, 0}, {25, FieldType::Float, 0}, {26, FieldType::Float, 0}, {27, FieldType::Float, 0} }},
        {2, { {0, FieldType::String, 0}, {1, FieldType::FixedString, 4}, {2, FieldType::Float, 0}, {3, FieldType::SignedLong, 0}, {4, FieldType::Float, 0}, {5, FieldType::Float, 0}, {6, FieldType::SignedLong, 0}, {7, FieldType::String, 0}, {8, FieldType::BitList, 5} }},
        {3, { {1, FieldType::String, 0}, {2, FieldType::StringList, 0}, {3, FieldType::StringList, 0}, {4, FieldType::String, 0}, {5, FieldType::BitList, 5} }},
        {4, { {1, FieldType::String, 0}, {2, FieldType::StringList, 0}, {3, FieldType::StringList, 0}, {4, FieldType::String, 0}, {5, FieldType::BitList, 5} }},
        {5, { {1, FieldType::String, 0}, {2, FieldType::StringList, 0}, {3, FieldType::StringList, 0}, {4, FieldType::String, 0}, {5, FieldType::BitList, 5} }},
    }},
    {"Units", {
        {1, { {0, FieldType::String, 0}, {1, FieldType::FloatList, 0}, {2, FieldType::FloatList, 0}, {3, FieldType::UnsignedLong, 0}, {4, FieldType::UnsignedLong, 0} }},
        {2, { {0, FieldType::String, 0}, {1, FieldType::UnsignedLong, 0}, {2, FieldType::Float, 0}, {3, FieldType::Float, 0}, {4, FieldType::UnsignedLong, 0}, {5, FieldType::UnsignedLong, 0}, {6, FieldType::Float, 0}, {7, FieldType::FloatList, 0}, {8, FieldType::Float, 0}, {9, FieldType::UnsignedLong, 0}, {10, FieldType::UnsignedLong, 0}, {11, FieldType::FloatList, 0}, {12, FieldType::TypeList, 20}, {13, FieldType::TypeList, 20}, {14, FieldType::TypeList, 20}, {15, FieldType::TypeList, 20}, {16, FieldType::TypeList, 20}, {17, FieldType::TypeList, 20}, {30, FieldType::String, 0}, {31, FieldType::StringList, 0}, {32, FieldType::StringList, 0}, {33, FieldType::Float, 0}, {34, FieldType::String, 0}, {35, FieldType::StringList, 0}, {36, FieldType::FloatList, 0}, {37, FieldType::UnsignedLong, 0}, {38, FieldType::UnsignedLong, 0}, {39, FieldType::FloatList, 0}, {40, FieldType::UnsignedLong, 0}, {41, FieldType::UnsignedLong, 0}, {42, FieldType::SignedLong, 0}, {43, FieldType::UnsignedLong, 0}, {44, FieldType::String, 0}, {45, FieldType::Byte, 0}, {46, FieldType::Float, 0}, {47, FieldType::UnsignedLong, 0}, {48, FieldType::UnsignedLong, 0}, {49, FieldType::UnsignedLong, 0}, {50, FieldType::UnsignedLong, 0} }},
        {3, { {0, FieldType::String, 0}, {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::UnsignedLong, 0}, {4, FieldType::SignedLong, 0}, {5, FieldType::Float, 0}, {6, FieldType::Float, 0}, {7, FieldType::Float, 0}, {8, FieldType::String, 0}, {9, FieldType::Float, 0}, {10, FieldType::Float, 0}, {11, FieldType::Float, 0}, {12, FieldType::Float, 0}, {13, FieldType::Float, 0}, {14, FieldType::Float, 0}, {15, FieldType::Float, 0}, {16, FieldType::Float, 0}, {17, FieldType::Float, 0}, {18, FieldType::UnsignedLong, 0}, {19, FieldType::Float, 0}, {20, FieldType::Float, 0}, {21, FieldType::Float, 0}, {22, FieldType::Float, 0}, {23, FieldType::Float, 0}, {24, FieldType::Float, 0}, {25, FieldType::FloatList, 0}, {26, FieldType::FloatList, 0}, {27, FieldType::TypeList, 21}, {28, FieldType::TypeList, 21}, {29, FieldType::StringList, 0}, {30, FieldType::FloatList, 0}, {31, FieldType::StringList, 0}, {32, FieldType::StringList, 0}, {33, FieldType::String, 0}, {34, FieldType::Float, 0}, {35, FieldType::Float, 0}, {36, FieldType::Float, 0}, {37, FieldType::Float, 0}, {38, FieldType::Float, 0}, {39, FieldType::UnsignedLong, 0}, {40, FieldType::Float, 0}, {41, FieldType::UnsignedLong, 0}, {42, FieldType::String, 0}, {43, FieldType::Float, 0} }},
        {4, { {0, FieldType::String, 0}, {1, FieldType::UnsignedLong, 0}, {2, FieldType::Float, 0}, {3, FieldType::Float, 0}, {4, FieldType::Float, 0}, {5, FieldType::Float, 0}, {6, FieldType::ByteList, 0}, {7, FieldType::ByteList, 0}, {8, FieldType::StringList, 0}, {9, FieldType::StringList, 0}, {10, FieldType::StringList, 0}, {11, FieldType::StringList, 0}, {12, FieldType::Float, 0}, {13, FieldType::UnsignedLong, 0}, {14, FieldType::Byte, 0} }},
        {20, { {0, FieldType::String, 0}, {1, FieldType::UnsignedLong, 0}, {2, FieldType::Float, 0}, {3, FieldType::Float, 0} }},
        {21, { {0, FieldType::Float, 0}, {1, FieldType::Float, 0}, {2, FieldType::Float, 0}, {3, FieldType::Float, 0} }},
    }},
    {"Acks", {
        {1, { {1, FieldType::String, 0}, {10, FieldType::AcksUniqueType, 20}, {11, FieldType::AcksUniqueType, 20}, {12, FieldType::AcksUniqueType, 20}, {13, FieldType::AcksUniqueType, 20}, {14, FieldType::AcksUniqueType, 20}, {15, FieldType::AcksUniqueType, 20}, {16, FieldType::AcksUniqueType, 20}, {17, FieldType::AcksUniqueType, 20}, {18, FieldType::AcksUniqueType, 20}, {19, FieldType::AcksUniqueType, 20}, {20, FieldType::AcksUniqueType, 20}, {21, FieldType::AcksUniqueType, 20}, {22, FieldType::AcksUniqueType, 20}, {23, FieldType::AcksUniqueType, 20}, {24, FieldType::AcksUniqueType, 20}, {25, FieldType::AcksUniqueType, 20}, {26, FieldType::AcksUniqueType, 20}, {27, FieldType::AcksUniqueType, 20}, {28, FieldType::AcksUniqueType, 20}, {29, FieldType::AcksUniqueType, 20}, {30, FieldType::AcksUniqueType, 20}, {31, FieldType::AcksUniqueType, 20}, {32, FieldType::AcksUniqueType, 21}, {33, FieldType::AcksUniqueType, 20}, {34, FieldType::AcksUniqueType, 20}, {35, FieldType::AcksUniqueType, 20}, {36, FieldType::AcksUniqueType, 20}, {37, FieldType::AcksUniqueType, 20}, {38, FieldType::AcksUniqueType, 20}, {39, FieldType::AcksUniqueType, 20}, {40, FieldType::AcksUniqueType, 20}, {41, FieldType::AcksUniqueType, 20}, {42, FieldType::AcksUniqueType, 20}, {43, FieldType::AcksUniqueType, 20}, {44, FieldType::AcksUniqueType, 20} }},
        {2, { {1, FieldType::String, 0}, {10, FieldType::AcksUniqueType, 20}, {11, FieldType::AcksUniqueType, 20}, {12, FieldType::AcksUniqueType, 20}, {13, FieldType::AcksUniqueType, 20}, {14, FieldType::AcksUniqueType, 20} }},
        {3, { {1, FieldType::String, 0}, {10, FieldType::AcksUniqueType, 20}, {11, FieldType::AcksUniqueType, 20} }},
        {20, { {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::String, 0} }},
        {21, { {1, FieldType::String, 0}, {2, FieldType::SignedLong, 0}, {3, FieldType::String, 0}, {4, FieldType::String, 0}, {10, FieldType::UnsignedLong, 0} }},
    }},
};

static const std::map<std::string, std::vector<std::pair<int, std::string>>> DBBLOCKS = {
    {"Items", { {1, "Materials"}, {2, "Weapons"}, {3, "Armors"}, {4, "QuickItems"}, {5, "QuestItems"}, {6, "LootItems"} }},
    {"Levers", { {1, "LeverPrototypes"} }},
    {"Perks", { {1, "Skills"}, {2, "Perks"} }},
    {"Prints", { {1, "BloodPrints"}, {2, "FootPrints"}, {3, "FirePrints"} }},
    {"Spells", { {1, "SpellPrototypes"}, {2, "SpellModifiers"}, {3, "S_Spells"}, {4, "S_Armors"}, {5, "S_Weapons"} }},
    {"Units", { {1, "HitLocations"}, {2, "RaceModels"}, {3, "Monsters"}, {4, "NPC"} }},
    {"Acks", { {1, "Answers"}, {2, "Cryes"}, {3, "Others"} }},
};