# um-bot's icons, all from assets/logo-source.png (the Sacred flower, quest item driadidol00: figure initqu10,
# texture quitem0010, rendered with
#   um-multitool viewer --figure initqu10 logo-source.png --texture quitem0010 --category questitems \
#                      --yaw 315 --pitch 30 --size 1024 --zoom 1.45
# Makes logo.png (512), logo-256.png (menus), um-bot.ico (Windows) and ../icon_data.hpp (the window icon).
# Run from tools/um-bot:  python3 assets/make_icons.py   (needs Pillow)
from PIL import Image
src = Image.open('assets/logo-source.png').convert('RGBA')
box = src.getbbox()                       # trim, then a square with a small margin
w, h = box[2] - box[0], box[3] - box[1]
side = int(max(w, h) * 1.06)
sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
sq.paste(src.crop(box), ((side - w) // 2, (side - h) // 2))
size = lambda n: sq.resize((n, n), Image.LANCZOS)
size(512).save('assets/logo.png')
size(256).save('assets/logo-256.png')
size(256).save('assets/um-bot.ico', sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (256, 256)])
with open('icon_data.hpp', 'w') as f:
    f.write('// The window icon: the Sacred flower (assets/logo.png), as RGBA pixels, top row first.\n'
            '// Generated by assets/make_icons.py; regenerate rather than edit.\n#pragma once\n\n#include <cstdint>\n\nnamespace logo {\n')
    for n in (64, 48, 32):
        px = size(n).tobytes()
        f.write('\nstatic const uint8_t kIcon%d[%d] = {\n' % (n, len(px)))
        for i in range(0, len(px), 24): f.write('    ' + ','.join(str(b) for b in px[i:i + 24]) + ',\n')
        f.write('};\n')
    f.write('\n} // namespace logo\n')
print('icons made, source', src.size, 'trimmed', (w, h))
