[Addon]
ShowAllQuests=1
AntiCrash=1
EnableLuaScripts=0
AttackAnimSpeed=1
DisableCrippledHL=1
ImproveInfoWindows=1

[RPG]
Perk Power Base=1.95
; Consider Modifier=200
; Consider Log Base=1.61

[LMP]
Lost Money=0.50
Lost XP=0

[DifficultyLevels]
Absorption=0.60
Absorption=0.33
Attack=1
Attack=0.66
Defence=0.70
Defence=0.66
