[Addon]
ShowAllQuests=1
AntiCrash=1
EnableLuaScripts=0
AttackAnimSpeed=1
DisableCrippledHL=1
ImproveInfoWindows=1

[AddonPerk]
Melee=120
Archery=120
Elemental=120
Sense=120
Astral=120

[RPG]
Perk Power Base=1.95
; Consider Modifier=200
; Consider Log Base=1.61

[LMP]
Lost Money=0.50
Lost XP=0

[DifficultyLevels]
Absorption=0.65
Absorption=0.33
Attack=1
Attack=0.66
Defence=0.75
Defence=0.66
