// Evil Islands script command signatures, used by the MOB script checker
// (mob_script_check.hpp). One row per command: name, return type, parameter
// types.
//
//   return type   v = returns nothing, f = float, s = string, o = object,
//                 g = group, ? = the reference sources disagree (accept any)
//   parameters    one letter per parameter: f = float, s = string, o = object,
//                 g = group, ? = type unknown (not checked). A leading '*' means
//                 "any number (at least two) of the following type".
//
// Sources, cross-checked against each other and against the script text of
// 237 shipped/community .mob files (the table produces no errors on any of
// them): the VGG editor's syntax.ini and scripts.htm, and MobExplorer's
// script_refs.txt (which also lists the commands the SpellAddon adds -
// Cos, DistancePointPoint, FloatToStr, GetArmor, GetObjectStringID, GetPlayerOfUnit, GetUnitExp, NearestUnit, Pow, Sin, StrLen, StrToFloat, UnitsNearPoint).
//
// Corrections applied on top of the sources: AddUnitUnderControl takes
// (float, object) (syntax.ini lists a third parameter that no map passes);
// CopyStats and InvokeAlarm had a parameter without a type (float);
// SetPlayerAggression takes two floats; StrCat is used with more than two
// strings in real maps; Stand, GameOver, GameOverMSG and DistanceUnitPoint
// are used by shipped maps but missing from every reference list.
#pragma once

struct MobScriptFunction {
    const char* name;
    char returns;
    const char* params;
};

static const MobScriptFunction kMobScriptFunctions[] = {
    {"ActivateTrap", 'v', "of"},
    {"Add", 'f', "ff"},
    {"AddLoot", 'v', "fss"},
    {"AddMob", 'v', "s"},
    {"AddObject", 'v', "go"},
    {"AddRectToArea", 'v', "fffff"},
    {"AddRoundToArea", 'v', "ffff"},
    {"AddUnitToParty", 'v', "fss"},
    {"AddUnitToServer", 'v', "sssfff"},
    {"AddUnitUnderControl", 'v', "fo"},
    {"AlarmPosX", 'f', "f"},
    {"AlarmPosY", 'f', "f"},
    {"AlarmTime", 'f', "f"},
    {"Any", 'f', "ogf"},
    {"AttachParticles", 'v', "fo"},
    {"AttachParticleSource", 'v', "ff"},
    {"Attack", 'v', "oo"},
    {"BlockUnit", 'v', "of"},
    {"Cast", 'v', "off"},
    {"CastSpellPoint", 'v', "sffff"},
    {"CastSpellUnit", 'v', "sffo"},
    {"ConsoleFloat", 'v', "f"},
    {"ConsoleString", 'v', "s"},
    {"CopyItems", 'v', "fss"},
    {"CopyLoot", 'v', "fss"},
    {"CopyStats", 'v', "fss"},
    {"Cos", 'f', "f"},
    {"Crawl", 'v', "o"},
    {"CreateFX", 'v', "fffffs"},
    {"CreateFXSource", 'v', "ffffffs"},
    {"CreateLightning", 'v', "ffffffff"},
    {"CreateParticleSource", 'v', "fffffs"},
    {"CreateParty", 'v', "fs"},
    {"CreatePointLight", 'v', "ffffffff"},
    {"CreateRandomizedFXSource", 'v', "fffffffffs"},
    {"DeleteArea", 'v', "f"},
    {"DeleteFXSource", 'v', "f"},
    {"DeleteLightning", 'v', "f"},
    {"DeleteParticleSource", 'v', "f"},
    {"DeletePointLight", 'v', "f"},
    {"DistancePointPoint", 'f', "ffff"},
    {"DistanceUnitPoint", 'f', "off"},
    {"DistanceUnitUnit", 'f', "oo"},
    {"Div", 'f', "ff"},
    {"EnableLever", 'v', "of"},
    {"EraseQuestItem", 'v', "ff"},
    {"Every", '?', "ogf"},
    {"FixItems", 'v', ""},
    {"FixWorldTime", 'v', "f"},
    {"FloatToStr", 's', "f"},
    {"Follow", 'v', "oo"},
    {"For", 'v', "og"},
    {"ForIf", 'v', "ogf"},
    {"GameOver", 'v', ""},
    {"GameOverMSG", 'v', "ss"},
    {"GetAIClass", 'f', "o"},
    {"GetArmor", 'f', "off"},
    {"GetBSZValue", 'f', "ff"},
    {"GetDiplomacy", 'f', "ff"},
    {"GetFutureX", 'f', "of"},
    {"GetFutureY", 'f', "of"},
    {"GetLeader", 'o', ""},
    {"GetLeverState", 'f', "o"},
    {"GetLootItemsCount", 'f', "f"},
    {"GetMercsNumber", 'f', "f"},
    {"GetMoney", 'f', "f"},
    {"GetObject", 'o', "f"},
    {"GetObjectByID", 'o', "s"},
    {"GetObjectByName", 'o', "s"},
    {"GetObjectID", 'f', "o"},
    {"GetObjectStringID", 's', "o"},
    {"GetPlayer", 'f', "o"},
    {"GetPlayerOfUnit", 'f', "o"},
    {"GetPlayerUnits", 'g', "f"},
    {"GetUnitExp", 'f', "o"},
    {"GetUnitOfPlayer", 'o', "ff"},
    {"GetWorldTime", 'f', ""},
    {"GetX", 'f', "o"},
    {"GetY", 'f', "o"},
    {"GetZ", 'f', "o"},
    {"GetZValue", 'f', "ff"},
    {"GiveDexterity", 'v', "of"},
    {"GiveIntelligence", 'v', "of"},
    {"GiveItem", 'v', "fs"},
    {"GiveMoney", 'v', "ff"},
    {"GiveQuestItem", 'v', "fs"},
    {"GiveSkill", 'v', "osf"},
    {"GiveStrength", 'v', "of"},
    {"GiveUnitQuestItem", 'v', "os"},
    {"GiveUnitSpell", 'v', "os"},
    {"GodMode", 'v', "ff"},
    {"GroupAdd", 'g', "gg"},
    {"GroupCross", 'g', "gg"},
    {"GroupHas", 'f', "go"},
    {"GroupSee", 'g', "g"},
    {"GroupSize", 'f', "g"},
    {"GroupSub", 'g', "gg"},
    {"GSDelVar", 'v', "fs"},
    {"GSGetVar", 'f', "fs"},
    {"GSSetVar", 'v', "fsf"},
    {"GSSetVarMax", 'v', "fsf"},
    {"Guard", 'v', "offf"},
    {"HaveItem", 'f', "ff"},
    {"HideObject", 'v', "of"},
    {"HP", 'f', "o"},
    {"Idle", 'v', "o"},
    {"InflictDamage", '?', "of"},
    {"InvokeAlarm", 'v', "fff"},
    {"IsAlarm", 'f', "f"},
    {"IsAlive", 'f', "o"},
    {"IsCameraPlaying", 'f', ""},
    {"IsDead", 'f', "o"},
    {"IsEnemy", 'f', "of"},
    {"IsEqual", 'f', "ff"},
    {"IsEqualString", 'f', "ss"},
    {"IsGreater", 'f', "ff"},
    {"IsInArea", 'f', "fff"},
    {"IsInSquare", 'f', "ffffff"},
    {"IsLess", 'f', "ff"},
    {"IsNight", 'f', ""},
    {"IsPlayerInDanger", 'f', "f"},
    {"IsPlayerInSafety", 'f', "f"},
    {"IsUnitBlocked", 'f', "o"},
    {"IsUnitInWater", 'f', "o"},
    {"IsUnitVisible", 'f', "o"},
    {"KillScript", 'v', ""},
    {"KillUnit", 'v', "o"},
    {"LeaveToZone", 'v', "fsf"},
    {"Lie", 'v', "o"},
    {"Mana", 'f', "o"},
    {"MaxHP", 'f', "o"},
    {"MaxMana", 'f', "o"},
    {"MoveParticleSource", 'v', "ffffff"},
    {"MovePointLight", 'v', "ffffff"},
    {"MoveToObject", 'v', "oo"},
    {"MoveToPoint", 'v', "off"},
    {"Mul", 'f', "ff"},
    {"NearestUnit", 'o', "ffff"},
    {"Not", 'f', "f"},
    {"PlayAnimation", 'v', "os"},
    {"PlayCamera", 'v', "s"},
    {"PlayerSee", '?', "f"},
    {"PlayFX", 'v', "ffffs"},
    {"PlayMovie", 'v', "s"},
    {"PlayMusic", 'v', "fs"},
    {"Pow", 'f', "ff"},
    {"Qfinish", 'v', ""},
    {"QObjArea", 'v', "f"},
    {"QObjGetItem", 'v', "f"},
    {"QObjKillGroup", 'v', "s"},
    {"QObjKillUnit", 'v', "s"},
    {"QObjSeeObject", 'v', "s"},
    {"QObjSeeUnit", 'v', "s"},
    {"QObjUse", 'v', "sf"},
    {"QStart", 'v', "s"},
    {"QuestComplete", 'v', "fs"},
    {"Random", 'f', "f"},
    {"RecalcMercBriefings", 'v', ""},
    {"RedeployParty", 'v', "f"},
    {"RemoveObject", 'v', "go"},
    {"RemoveObjectFromServer", 'v', "o"},
    {"RemoveParty", 'v', "fs"},
    {"RemoveQuestItem", 'v', "of"},
    {"RemoveUnitFromControl", 'v', "fo"},
    {"RemoveUnitFromParty", 'v', "fs"},
    {"RemoveUnitFromServer", 'v', "o"},
    {"ResetTarget", 'v', "o"},
    {"Rest", 'v', "o"},
    {"RotateTo", 'v', "off"},
    {"Run", 'v', "o"},
    {"RunWorldTime", 'v', "f"},
    {"SendEvent", 'v', "ff"},
    {"SendStringEvent", 'v', "fs"},
    {"Sentry", 'v', "off"},
    {"SetBackgroudColor", 'v', "fff"},
    {"SetCameraOrientation", 'v', "f"},
    {"SetCameraPosition", 'v', "fff"},
    {"SetCP", 'v', "offf"},
    {"SetCPFast", 'v', "offf"},
    {"SetCurrentParty", 'v', "fs"},
    {"SetDiplomacy", 'v', "fff"},
    {"SetDirectionToObject", 'v', "f"},
    {"SetEnemy", 'v', "of"},
    {"SetParticleSourceSize", 'v', "ff"},
    {"SetPlayer", 'v', "of"},
    {"SetPlayerAggression", 'v', "ff"},
    {"SetScience", 'v', "offffff"},
    {"SetSpellAggression", 'v', "of"},
    {"SetSunLight", 'v', "fffffffff"},
    {"SetWaterLevel", 'v', "fff"},
    {"SetWind", 'v', "ffff"},
    {"ShowBitmap", 'v', "fs"},
    {"ShowCredits", 'v', "s"},
    {"Sin", 'f', "f"},
    {"Sleep", 'v', "f"},
    {"SleepUntil", 'v', "f"},
    {"SleepUntilIdle", 'v', "o"},
    {"Stand", 'v', "o"},
    {"Standt", 'v', "o"},
    {"StartAnimation", 'v', "os"},
    {"StrCat", 's', "*s"},
    {"StrLen", 'f', "s"},
    {"StrToFloat", 'f', "s"},
    {"Sub", 'f', "ff"},
    {"Sum", 'f', "ogf"},
    {"SwitchLeverState", 'v', "of"},
    {"SwitchLeverStateEx", 'v', "off"},
    {"UMAg", 'v', "of"},
    {"UMAggression", 'v', "o"},
    {"UMClear", 'v', "o"},
    {"UMCorpseWatcher", 'v', "o"},
    {"UMFear", 'v', "of"},
    {"UMFollow", 'v', "oo"},
    {"UMGuard", 'v', "offf"},
    {"UMGuardEx", 'v', "offff"},
    {"UMPatrol", 'v', "o"},
    {"UMPatrolAddPoint", 'v', "off"},
    {"UMPatrolAddPointLook", 'v', "offf"},
    {"UMPatrolClear", 'v', "o"},
    {"UMPlayer", 'v', "o"},
    {"UMRevenge", 'v', "o"},
    {"UMSentry", 'v', "off"},
    {"UMStandard", 'v', "o"},
    {"UMSuspection", 'v', "o"},
    {"UnitInSquare", 'f', "offff"},
    {"UnitSee", 'g', "o"},
    {"UnitsNearPoint", 'g', "ffff"},
    {"WaitEndAnimation", 'v', ""},
    {"WaitSegment", 'v', "f"},
    {"Walk", 'v', "o"},
    {"WasLooted", 'f', "o"},
};
