name: Master Auto Build
permissions:
    contents: write
on:
  pull_request_target:
    types:
      - closed
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        run: |
          VERSION=$(cat "resources/universal-mod/version/mod-version.txt" | tr -d ' \n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract commit Hash
        run: |
          COMMITHASH=$(grep -oE '[0-9a-f]{7,}' "resources/universal-mod/res-texts/texts-eng_res/string version_name" | head -n 1)
          echo "COMMITHASH=$COMMITHASH" >> $GITHUB_ENV

      - name: Declare ZIPNAME and echo the other variables
        run: |
          ZIPNAME="Universal-Mod-$VERSION-$COMMITHASH.zip"
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV

      - name: Create ZIP Archive
        run: |
          zip -r $ZIPNAME "Universal-Mod"
          ls -lah

      - name: Upload release
        uses: ncipollo/release-action@v1.12.0
        # Docs here : https://github.com/marketplace/actions/create-release
        with:
          artifacts: ${{ env.ZIPNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true
          name: Universal Mod ${{ env.VERSION }} ${{ env.COMMITHASH }}
          tag: ${{ env.VERSION }}
          prerelease: false
          generateReleaseNotes: true
          allowUpdates: true
          removeArtifacts: true
